export const FETCH_LEAGUES = "FETCH_LEAGUES";

export const FETCH_MATCHES = "FETCH_MATCHES";

export const FETCH_RECENT_MATCHES = "FETCH_RECENT_MATCHES";

export const FETCH_TEAM = "FETCH_TEAM";

export const FETCH_PLAYINGTEAMS = "FETCH_PLAYINGTEAMS";

export const LOADING_STATE = "LOADING_STATE";

export const LEAGUE_NAME = "LEAGUE_NAME";

export const POST_USER = "POST_USER";

export const UPDATE_USER = "UPDATE_USER";

export const FETCH_ICONS = "FETCH_ICONS";

export const FETCH_PLAYER = "FETCH_PLAYER";

export const PICK_PLAYER = "PICK_PLAYER";

export const DELETE_PLAYER = "DELETE_PLAYER";

export const GET_FANTASY_TEAM = "GET_FANTASY_TEAM";

export const FETCH_TOURNAMENTS = "FETCH_TOURNAMENTS";

export const FETCH_TOURNAMENT = "FETCH_TOURNAMENT";

export const ADD_TOURNAMENT = "ADD_TOURNAMENT";

export const DELETE_TOURNAMENT = "DELETE_TOURNAMENT";

export const END_TOURNAMENT = "END_TOURNAMENT";

export const TEAMS_IN_TOURNAMENT = "TEAMS_IN_TOURNAMENT";

export const REGISTER_TOURNAMENT = "REGISTER_TOURNAMENT";

export const REGISTERED_USERS = "REGISTERED_USERS";

export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";

export const DELETE_MESSAGE = "DELETE_MESSAGE";

export const FETCH_SHOP = "FETCH_SHOP";
